version: '2'

services:
  web:
    build: ./app
    command: gunicorn vidamia.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/django-src/:/usr/src/app/django-src/
      - static_volume:/usr/src/app/django-src/staticfiles
      - media_volume:/usr/src/app/django-src/mediafiles
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file: .env.db
  nginx:
    build: ./nginx
    volumes:
      # - ./nginx/angular-src/vidamia/dist/vidamia/:/usr/src/app/angular-src
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: