# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 14:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_minus_percent',
            field=models.PositiveIntegerField(default=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
